version: '3.8'

services:
  kinfitr-app:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./config_outputs:/srv/shiny-server/kinfitr_app/config_outputs
      - ./data:/srv/shiny-server/kinfitr_app/data
    environment:
      - SHINY_LOG_LEVEL=TRACE
    restart: unless-stopped